// <auto-generated />
using DigitalGradebook.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalGradebook.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503152128_SeedInitialStudents")]
    partial class SeedInitialStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DigitalGradebook.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("DigitalGradebook.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mentions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentMom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneDad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneMom")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = "2015-05-12",
                            Cnp = "6150512410011",
                            Email = "maria.p@student.ro",
                            FirstName = "Maria",
                            LastName = "Popa",
                            Mentions = "A very diligent student with great attention to detail.",
                            ParentDad = "Popa Viorel",
                            ParentMom = "Popa Elena",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148510",
                            Username = "MariaP2015"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = "2015-08-23",
                            Cnp = "6150823410022",
                            Email = "maia.i@student.ro",
                            FirstName = "Maia",
                            LastName = "Ionescu",
                            Mentions = "Maia is making rapid progress in mathematics.",
                            ParentDad = "Ionescu Dan",
                            ParentMom = "Ionescu Carmen",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148511",
                            Username = "MaiaI"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = "2016-02-05",
                            Cnp = "5160205410033",
                            Email = "eduard.s@student.ro",
                            FirstName = "Eduard",
                            LastName = "Szabo",
                            Mentions = "Eduard needs to focus more on his reading skills.",
                            ParentDad = "Szabo Levente",
                            ParentMom = "Szabo Ionela",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148512",
                            Username = "EdiSz"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = "2015-11-14",
                            Cnp = "5151114410044",
                            Email = "tiberiu.p@student.ro",
                            FirstName = "Tiberiu",
                            LastName = "Pop",
                            Mentions = "Tiberiu requires additional support with his writing.",
                            ParentDad = "Pop Ovidiu",
                            ParentMom = "Pop Maria",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148513",
                            Username = "TibiP"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = "2016-03-29",
                            Cnp = "6160329410055",
                            Email = "denisa.n@student.ro",
                            FirstName = "Denisa",
                            LastName = "Negru",
                            Mentions = "A bright presence in the classroom and very active.",
                            ParentDad = "Negru Marin",
                            ParentMom = "Negru Adina",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148514",
                            Username = "DeniN"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = "2015-07-01",
                            Cnp = "6150701410066",
                            Email = "ionela.d@student.ro",
                            FirstName = "Ionela",
                            LastName = "Dumbravean",
                            Mentions = "Ionela draws beautifully during breaks.",
                            ParentDad = "Dumbravean Ioan",
                            ParentMom = "Dumbravean Ana",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148515",
                            Username = "IonelaD"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = "2015-09-18",
                            Cnp = "5150918410077",
                            Email = "andrei.v@student.ro",
                            FirstName = "Andrei",
                            LastName = "Vasilescu",
                            Mentions = "Andrei has started to participate more during lessons.",
                            ParentDad = "Vasilescu George",
                            ParentMom = "Vasilescu Mirela",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148516",
                            Username = "AndreiV"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = "2015-10-10",
                            Cnp = "6151010410088",
                            Email = "alina.m@student.ro",
                            FirstName = "Alina",
                            LastName = "Munteanu",
                            Mentions = "Alina is the leader of the project team.",
                            ParentDad = "Munteanu Paul",
                            ParentMom = "Munteanu Silvia",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148517",
                            Username = "AlinaM"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = "2016-01-22",
                            Cnp = "5160122410099",
                            Email = "florin.r@student.ro",
                            FirstName = "Florin",
                            LastName = "Radu",
                            Mentions = "Florin's efforts are clearly visible in history class.",
                            ParentDad = "Radu Cristian",
                            ParentMom = "Radu Ioana",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148518",
                            Username = "FlorinR"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = "2016-04-15",
                            Cnp = "6160415410100",
                            Email = "ana.g@student.ro",
                            FirstName = "Ana",
                            LastName = "Georgescu",
                            Mentions = "Ana excels in all subjects this semester.",
                            ParentDad = "Georgescu Mihai",
                            ParentMom = "Georgescu Dana",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148519",
                            Username = "AnaGeo"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = "2015-12-03",
                            Cnp = "5151203410111",
                            Email = "bogdan.s@student.ro",
                            FirstName = "Bogdan",
                            LastName = "Stanescu",
                            Mentions = "Bogdan is a very fair and reliable teammate.",
                            ParentDad = "Stanescu Alex",
                            ParentMom = "Stanescu Raluca",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148520",
                            Username = "BogdanS"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = "2015-06-19",
                            Cnp = "6150619410122",
                            Email = "elena.d@student.ro",
                            FirstName = "Elena",
                            LastName = "Dumitrescu",
                            Mentions = "Elena has a very rich vocabulary for her age.",
                            ParentDad = "Dumitrescu Lucian",
                            ParentMom = "Dumitrescu Vera",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148521",
                            Username = "ElenaD"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = "2016-02-27",
                            Cnp = "5160227410133",
                            Email = "radu.p@student.ro",
                            FirstName = "Radu",
                            LastName = "Popescu",
                            Mentions = "Radu needs to practice the multiplication table more often.",
                            ParentDad = "Popescu Matei",
                            ParentMom = "Popescu Laura",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148522",
                            Username = "RaduP"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = "2015-05-11",
                            Cnp = "6150511410144",
                            Email = "andreea.i@student.ro",
                            FirstName = "Andreea",
                            LastName = "Ionescu",
                            Mentions = "Andreea is shy, but she is making wonderful progress.",
                            ParentDad = "Ionescu Radu",
                            ParentMom = "Ionescu Gina",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148523",
                            Username = "AndreeaI"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = "2015-08-30",
                            Cnp = "6150830410155",
                            Email = "ioana.v@student.ro",
                            FirstName = "Ioana",
                            LastName = "Vasilescu",
                            Mentions = "Ioana is very creative during music lessons.",
                            ParentDad = "Vasilescu Sorin",
                            ParentMom = "Vasilescu Monica",
                            PhoneDad = "",
                            PhoneMom = "",
                            UniqueNumber = "7Y148524",
                            Username = "IoanaV"
                        });
                });

            modelBuilder.Entity("DigitalGradebook.Domain.Entities.Grade", b =>
                {
                    b.HasOne("DigitalGradebook.Domain.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DigitalGradebook.Domain.Entities.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
